### ISSUE TITLE
Bootstrap Data View with Summary Facet Throws NPE

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/XPagesExtensionLibrary#47]
java.lang.NullPointerException
at com.ibm.xsp.theme.bootstrap.renderkit.html.extlib.data.DataViewRenderer.writeDataColumn(DataViewRenderer.java:317)
at com.ibm.xsp.extlib.renderkit.html_extended.data.DataViewRenderer.writeStandardRow(DataViewRenderer.java:820)
at com.ibm.xsp.extlib.renderkit.html_extended.data.DataViewRenderer.writeRow(DataViewRenderer.java:595)
at com.ibm.xsp.extlib.renderkit.html_extended.data.AbstractDataViewRenderer.writeRows(AbstractDataViewRenderer.java:817)
at com.ibm.xsp.extlib.renderkit.html_extended.data.DataViewRenderer.writeRows(DataViewRenderer.java:573)
at com.ibm.xsp.extlib.renderkit.html_extended.data.DataViewRenderer.writeContent(DataViewRenderer.java:271)

Caused by viewDef.hasSummary returning true, because summary facet in use. Check on line 317 just does `viewDef.summaryColumn.getColumnTitle()`. But there's no summary column, just a summary facet.

I'm creating a pull request for the fix.

**Comment by paulswithers** [comment]
Issue can be reproduced by having a DataView with a summary facet and no summary column

**Comment by briangleeson** [comment]
Fix submitted in ExtLib release 17
